[build]
  base = "."
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://startech-management.onrender.com"

# Create dist directory if it doesn't exist
[build.processing]
  skip_processing = false
